# -*- coding: utf-8 -*-
"""Untitled46.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14dft6sC-5OUbJOy1EXr_ul7yvpclaYUg
"""

import numpy as np
import cv2

!pip install keras-facenet

from keras_facenet import FaceNet
model = FaceNet()

img = cv2.imread('test.jpg')

cv2.resize(img,(160,160))

img = np.asarray(img)

img = img.astype('float32')/255.0

img

img = np.expand_dims(img, axis=0)

embed = model.embeddings(img)

embed.shape